#pragma once

// From glfw3.h
#define GLOB_MOUSE_BUTTON_1         0
#define GLOB_MOUSE_BUTTON_2         1
#define GLOB_MOUSE_BUTTON_3         2
#define GLOB_MOUSE_BUTTON_4         3
#define GLOB_MOUSE_BUTTON_5         4
#define GLOB_MOUSE_BUTTON_6         5
#define GLOB_MOUSE_BUTTON_7         6
#define GLOB_MOUSE_BUTTON_8         7
#define GLOB_MOUSE_BUTTON_LAST      GLOB_MOUSE_BUTTON_8
#define GLOB_MOUSE_BUTTON_LEFT      GLOB_MOUSE_BUTTON_1
#define GLOB_MOUSE_BUTTON_RIGHT     GLOB_MOUSE_BUTTON_2
#define GLOB_MOUSE_BUTTON_MIDDLE    GLOB_MOUSE_BUTTON_3 